export const FETCH_QUESTION = "FETCH_QUESTION";
export const INCREMENT_QUESTIONS_COUNT = "INCREMENT_QUESTIONS_COUNT";
export const RELOCATE_FROM_PROPOSITION_TO_BOARD = "RELOCATE_FROM_PROPOSITION_TO_BOARD";
export const RELOCATE_FROM_BOARD_TO_PROPOSITION = "RELOCATE_FROM_BOARD_TO_PROPOSITION";
export const CHECK_ANSWER = "CHECK_ANSWER";
